/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dat' at '7/14/17 3:08 AM' with Gradle 2.14.1
 *
 * @author dat, @date 7/14/17 3:08 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
